travis:
  secure:
    BINSTAR_TOKEN: CIbJDJs/Q6qjeGfD0EzE0iXr32sKgVxy04HvSZRHjlb5WCq7E+1m4GcaUvzvYes389lgcDaTYE1HR7sS3ZlekwLJvZzMnj+ore1uW0YUi1KOxgtrUGZFa/OoYk47msYhjC85vScpuTepVG24HZAyZziGm0cdA72URufDXI6VxkKEDb4VBNXmoVwPTTGBdDp1Sz03a7CKnhMrioC1IqPMs34Oa35h4mqaCY9H/bDIcfCPV9VkZKBjQBeTve2ZcXa1kFtuxw6JYfToTTMZhNRtVEaF04VSibONKYWoyGP1vEcmYF2/w9CJ/QMwHOApoZ+fk8B/++vd9PZWhomRTMTqYax6AC5FJfePXIFsIC+J5DwBM7ErLft1qHlovsR1qGLMLfQRHPRHL+W2Vkw99cN/GP/SEKN2+fKxUCBI/IZ7zOzRVZXZD8RyVUojCHlwmeLdR+7wYwz8CaxOfnQGTQTAKwccyMnDx/+sat5x08DRdxJSU9XpvFi0vtklAo1ZTZasQItH2wckGKKg4ZcCBUOWCUGlUAN+fuK3MFMSR+/WNAmZuykY+rSW9t4WC4/+fEmmMNg0DmauEIijNxsbpWq9vxxiX27PBhLKTMNoNO7qNMrkswIxpoWAxucCaGRiudonrBuyzAlMhispw3JtjFIHxOjowlcbuadb01ARYzbLZVQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
