travis:
  secure:
    BINSTAR_TOKEN: H9KiIQUTMzmFrAevbsa5IyPKo1hxwJTVPoO5netBQ6jBx1wo7fme6PC8d3TLnj4tSDjBgsmVmtRCPq5vLkgF0eaiO3Chf7CiPCEOo0bkGiBInyPdpWl7v+W8C1wZ6tYjFcpsv6OEykalJDbsY4iZcnzT8Xc5Zk46M/RWRaHdeSK+wVH1CGnhFbS4i2GQG9Qm2fEKeuWfquQBc3Kac3bpdoQRIOOWxF+Va0vM08U9yovXHHMdblbyCSnlXSBlYYUpN6AcTuTy1EWm2qhyx9ZsI/6sQEo3z2ezlv7+B7axLc4vAaXXsDrN/3KhbMnusodD8yXHDDPe2qtQXcI0TBov8T3FYVeKO9cTw86XgAU3d3XSAqg3UK5usnykHhO2QHBNH1/ODNNna2jSfK7zyodYVqkMMBByOgwdt/gWuVABvPpl+PS/SXMc0ue8APfzOxHX//1SXvSP+Nj1niugmR5jMZ8EJ4Pnheul8OZMw4yA1melzfHvqGbu34Dkv2GCUC13tKY3FyOkIIv+0s0emRx0YtxvKD+90Ie3HmgINvF6RIK2qiuv7g8aogASnazj2LFrmJbqHXAqMDONKEudRr3LSpHvxIVvs50utSygVtR80IOTt0DNePq5fLmrCP78/3TbMwrrbpfwPbP8n4pN9Bu3E9/SYS0aFgxwBVX+D+C+VEY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
